admindashboard/urls.py
from django.conf.urls import patterns, url
# from organizations.backends import invitation_backend
import views
from registration.backends.default.views import ActivationView
from django.contrib.auth.views import *

urlpatterns = patterns('',

    url(r'^$', views.index, name='index'),

    url(r'^customers/$', views.CustomersListView.as_view(), name='customers'),
    url(r'^customers/create$', views.CustomerCreateView.as_view(), name='customercreate'),
    url(r'^customers/(?P<pk>\d+)/update$', views.CustomerUpdateView.as_view(), name='customerupdate'),
    url(r'^customers/(?P<pk>[-_\w]+)/$', views.CustomerView.as_view(), name='customer'),
    url(r'^customers/(?P<pk>\d+)/delete$', views.CustomerDeleteView.as_view(), name='customerdelete'),

    url(r'^customers/(?P<pk>\d+)/fields/create$', views.CustomerFieldCreate.as_view(), name='customerfieldcreate'),
    url(r'^customers/(?P<customer_id>\d+)/fields/(?P<pk>\d+)/delete$', views.CustomerFieldDeleteView.as_view(), name='customerfielddelete'),
    url(r'^customers/(?P<customer_id>\d+)/fields/(?P<pk>\d+)/update$', views.CustomerFieldUpdateView.as_view(), name='customerfieldupdate'),
    url(r'^customers/(?P<customer_id>\d+)/fields/(?P<pk>\d+)$', views.CustomerFieldDetailView.as_view(), name='customerfield'),

    url(r'^users/$', views.UsersListView.as_view(), name='users'),
    url(r'^users/create$', views.UserCreateView.as_view(), name='usercreate'),
    url(r'^users/(?P<pk>\d+)/update$', views.UserUpdateView.as_view(), name='userupdate'),
    url(r'^users/(?P<pk>[-_\w]+)/$', views.UserDetailView.as_view(), name='user'),

    url(r'^users/(?P<pk>\d+)/delete$', views.UserDeleteView.as_view(), name='userdelete'),

    url(r'^imagetypes$', views.ImageTypeListView.as_view(), name='imagetypes'),
    url(r'^imagetypes/(?P<pk>[-_\w]+)/$', views.ImageTypeView.as_view(), name='imagetype'),
    url(r'^imagetypes/create$', views.ImageTypeCreateView.as_view(), name='imagetypecreate'),
    url(r'^imagetypes/(?P<pk>\d+)/update$', views.ImageTypeUpdateView.as_view(), name='imagetypeupdate'),
    url(r'^imagetypes/(?P<pk>\d+)/delete$', views.ImageTypeDeleteView.as_view(), name='imagetypedelete'),
)

eiwa/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.generic.base import RedirectView
from django.contrib import admin
from django.core.urlresolvers import reverse_lazy
from django.conf.urls.static import static
from django.conf import settings

admin.autodiscover()



urlpatterns = patterns('',
    url(r'^ui/admin/', include(admin.site.urls)),
    url(r'^$', RedirectView.as_view(url=reverse_lazy('auth:login'))),
    url(r'^ui/', include('ui.urls', namespace='ui')),
    url(r'^auth/', include('login.urls', namespace='auth')),
    url(r'^admindashboard/', include('admindashboard.urls', namespace='admindashboard')),
)

# urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

ui/urls.py
from django.conf.urls import patterns, url
# from organizations.backends import invitation_backend
from .views import views

urlpatterns = patterns('',

    url(r'^(?P<client_id>\d+)/fields/$', views.customer_fields, name='fields'),
    url(r'^(?P<client_id>\d+)/fields/(?P<field_id>\d+)$', views.customer_field, name='field'),
    url(r'^(?P<client_id>\d+)/fields/(?P<field_id>\d+)/bucket/tabledata/$', views.customer_field_bucket_tabledata, name='field_bucket_tabledata'),
    url(r'^(?P<client_id>\d+)/fields/(?P<field_id>\d+)/border/tabledata/$', views.customer_field_border_tabledata, name='field_border_tabledata'),
    url(r'^(?P<client_id>\d+)/fields/(?P<field_id>\d+)/ol/$', views.customer_field_ol, name='fieldol'),
    url(r'^(?P<client_id>\d+)/fields/(?P<field_id>\d+)/env/kml/$', views.customer_field_env_kml, name='fieldenvkml'),
    url(r'^(?P<client_id>\d+)/fields/(?P<field_id>\d+)/border/kml/$', views.customer_field_border_kml, name='fieldborderkml'),
    url(r'^(?P<client_id>\d+)/fields/(?P<field_id>\d+)/bucket/tabledata/csv$', views.customer_field_bucket_data_export, name='field_bucket_tabledata_csv'),
    url(r'^(?P<client_id>\d+)/fields/(?P<field_id>\d+)/border/tabledata/csv$', views.customer_field_border_data_export, name='field_border_tabledata_csv'),

)

admindashboard/forms.py
from django.forms import ModelForm, DateInput, DateField
from django.forms.models import inlineformset_factory, BaseInlineFormSet
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from functools import partial

date_format = '%d/%m/%Y'
DateInputCustom = partial(
    DateInput, format=(date_format), attrs={'class': 'datepicker'})

from ui.models import Field, ProductiveUnitImage, OrganizationUser

class CustomerFieldForm(ModelForm):

    class Meta:
        model = Field
        exclude = ('customer', 'delete', )


class UserCreateForm(UserCreationForm):

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email', 'username',
                  'password1', 'password2', 'groups', )


class UserEditForm(UserChangeForm):

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email', 'username',
                  'password', 'groups', 'is_active', )


class NoEmptyInlineModelFormSet(BaseInlineFormSet):

    def __init__(self, *args, **kwargs):
        super(NoEmptyInlineModelFormSet, self).__init__(*args, **kwargs)
        for form in self.forms:
            form.empty_permitted = False


class ProductiveUnitImageForm(ModelForm):
    date_taken = DateField(
        widget=DateInputCustom(), input_formats=(date_format,))

    class Meta:
        model = ProductiveUnitImage
        fields = '__all__'

OrganizationUserFormSet = inlineformset_factory(User, OrganizationUser,
                                                can_delete=False,
                                                extra=1,
                                                formset=NoEmptyInlineModelFormSet)

ProductiveUnitImageFormSet = inlineformset_factory(Field, ProductiveUnitImage,
                                                   form=ProductiveUnitImageForm,
                                                   can_delete=True,
                                                   extra=1, max_num=1)

admindashboard/views.py
from django.shortcuts import (render, get_object_or_404)
from django.core.urlresolvers import reverse_lazy, reverse
from django.contrib.auth.decorators import login_required
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages
from django.utils.translation import ugettext_lazy as _
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.contrib.auth.models import User
from django.contrib.sites.models import RequestSite

from registration.backends.default.views import RegistrationView
from braces.views import GroupRequiredMixin

from ui.models import Field, Customer, ImageType
from forms import *
from ui.models import BaseGeom


class AdminRequiredMixin(GroupRequiredMixin):
    group_required = u"Admin"


@login_required
def index(request):
    return render(request, 'admindashboard/adminDashboard.html')


class UsersListView(AdminRequiredMixin, ListView):
    model = User
    template_name = "admindashboard/users/user_list.html"


class UserCreateView(AdminRequiredMixin, RegistrationView):
    model = User
    template_name = "admindashboard/users/user_form.html"
    form_class = UserCreateForm

    def get_context_data(self, **kwargs):
        context = super(UserCreateView, self).get_context_data(**kwargs)
        if self.request.POST:
            context['organizationForm'] = OrganizationUserFormSet(self.request.POST)
        else:
            context['organizationForm'] = OrganizationUserFormSet()
        return context

    def register(self, request, **cleaned_data):
        context = self.get_context_data()
        organizationuser_form = context['organizationForm']
        if organizationuser_form.is_valid():
            #self.object = RegistrationManager.create_inactive_user
            #(form['username'], form['email'], form['password1'], None, False)
            context['site'] = RequestSite(request)
            self.object = super(UserCreateView, self).register(request, **cleaned_data)

            organizationuser_form.instance = self.object
            organizationuser_form.save()
            #self.object.registrationprofile.send_activation_email(None)
            return redirect(self.get_success_url(request, self.object))
        else:
            return self.render_to_response(self.get_context_data(
                form=form, organizationForm=organizationuser_form))

    def get_success_url(self, request, user):
        return reverse('admindashboard:users')


class UserDeleteView(AdminRequiredMixin, DeleteView):
    model = User
    template_name = "admindashboard/generic_confirm_delete.html"

    def get_success_url(self):
        return reverse('admindashboard:users')

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(UserDeleteView, self).get_context_data(**kwargs)
        context['object_class'] = 'user'
        context['referer'] = "admindashboard:users"
        return context


class UserUpdateView(AdminRequiredMixin, UpdateView):
    model = User
    template_name = 'admindashboard/users/user_form.html'
    form_class = UserEditForm

    def get_context_data(self, **kwargs):
        context = super(UserUpdateView, self).get_context_data(**kwargs)
        if self.request.POST:
            context['organizationForm'] = OrganizationUserFormSet(
                self.request.POST, instance=self.object)
        else:
            context['organizationForm'] = OrganizationUserFormSet(instance=self.object)
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        organizationuser_form = context['organizationForm']
        if organizationuser_form.is_valid():
            self.object = form.save()
            organizationuser_form.save()
            return redirect(self.get_success_url())
        else:
            return self.render_to_response(
                self.get_context_data(form=form, organizationForm=organizationuser_form))

    def get_success_url(self):
        return reverse('admindashboard:users')


class UserDetailView(AdminRequiredMixin, DetailView):
    model = User
    template_name = 'admindashboard/users/user_detail.html'

    def get_success_url(self):
        return self.object.organizationuser.get_edit_url()

class CustomersListView(AdminRequiredMixin, ListView):
    queryset = Customer.objects.order_by('name')
    paginate_by = 10
    template_name = "admindashboard/customers/customer_list.html"

class CustomerView(AdminRequiredMixin, DetailView):
    model = Customer
    fields = ['name']
    template_name = "admindashboard/customers/customer_detail.html"


class CustomerCreateView(AdminRequiredMixin, CreateView):
    model = Customer
    fields = ['name']
    template_name = "admindashboard/customers/customer_form.html"

    def get_success_url(self):
        return self.object.get_edit_url()


class CustomerUpdateView(AdminRequiredMixin, UpdateView):
    model = Customer
    success_url = reverse_lazy('admindashboard:customers')
    fields = ['name']
    template_name = "admindashboard/customers/customer_form.html"


class CustomerDeleteView(AdminRequiredMixin, DeleteView):
    model = Customer
    success_url = reverse_lazy('admindashboard:customers')
    template_name = "admindashboard/generic_confirm_delete.html"

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(CustomerDeleteView, self).get_context_data(**kwargs)
        context['object_class'] = 'customer'
        context['referer'] = "admindashboard:customers"
        # context['referer_params'] = None
        return context



class CustomerFieldCreate(AdminRequiredMixin, SuccessMessageMixin, CreateView):
    model = Field
    form_class = CustomerFieldForm
    template_name = 'admindashboard/customers/fields/field_form.html'
    success_message = _('Productive Unit "%(name)s" has been created.')

    def dispatch(self, *args, **kwargs):
        self.customer = get_object_or_404(Customer, pk=kwargs['pk'])
        return super(CustomerFieldCreate, self).dispatch(*args, **kwargs)

    def get_form(self, form_class):
        form = super(CustomerFieldCreate, self).get_form(form_class)
        form.instance.customer = self.customer
        return form

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(CustomerFieldCreate, self).get_context_data(**kwargs)
        context['customer'] = self.customer

        if self.request.POST:
            context['images_form'] = ProductiveUnitImageFormSet(self.request.POST,
                                                                self.request.FILES)
        else:
            context['images_form'] = ProductiveUnitImageFormSet()

        return context

    def form_valid(self, form):
        ctx = self.get_context_data()
        images = ctx['images_form']

        if images.is_valid():
            self.object = form.save()
            images.instance = self.object
            for image in images:
                image.instance.productive_unit = self.object
            images.save()

            warning_messages = BaseGeom.process_files(self.object)
            for message in warning_messages:
                messages.warning(self.request, message)

            return super(CustomerFieldCreate, self).form_valid(form)
        else:
            return super(CustomerFieldCreate, self).form_invalid(form)

    def get_success_url(self):
        return self.object.customer.get_edit_url()


class CustomerFieldDeleteView(AdminRequiredMixin, DeleteView):
    model = Field
    template_name = "admindashboard/generic_confirm_delete.html"

    def get_success_url(self):
        return self.object.customer.get_edit_url()

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(CustomerFieldDeleteView, self).get_context_data(**kwargs)
        context['object_class'] = 'field'
        context['referer'] = "admindashboard:customerupdate"
        context['referer_params'] = kwargs['object'].customer.id
        return context


class CustomerFieldUpdateView(AdminRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Field
    template_name = 'admindashboard/customers/fields/field_update_form.html'
    success_message = _('Productive Unit "%(name)s" has been updated.')

    def form_valid(self, form):
        ctx = self.get_context_data()
        images = ctx['images_form']

        if images.is_valid():
            self.object = form.save()
            images.instance = self.object
            obj = images.save()
            warning_messages = BaseGeom.process_files(self.object)
            for message in warning_messages:
                messages.warning(self.request, message)

            return super(CustomerFieldUpdateView, self).form_valid(form)
        else:
            return super(CustomerFieldUpdateView, self).form_invalid(form)

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(CustomerFieldUpdateView, self).get_context_data(**kwargs)

        if self.request.POST:
            context['images_form'] = ProductiveUnitImageFormSet(self.request.POST,
                                                                self.request.FILES,
                                                                instance=self.object)

        if 'images_form' not in context:
            context['images_form'] = ProductiveUnitImageFormSet(instance=self.object)

        return context

    def get_success_url(self):
        return self.object.customer.get_edit_url()


class CustomerFieldDetailView(AdminRequiredMixin, DetailView):
    model = Field

admindashboard/templates/admindashboard/images/imagetype_detail.html
{% extends 'admindashboard/base.html' %}
{% load i18n %}
{% load widget_tweaks %}
{% load django_bootstrap_breadcrumbs %}
{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb "Image Types" "admindashboard:imagetypes" %}
{% endblock %}

{% block admin_page_content %}

  <div class="panel panel-primary">
   <div class="panel-heading">
  {% trans "Image Type Details" %}
   </div>
    <div class="panel-body">
    {% trans "Name" %}: {{imagetype.name}}<br>
    {% trans "Description" %}: {{imagetype.description}}<br>
    {% trans "Display Name" %}: {{imagetype.display_name}}<br>
<br/>
<br/>
<br/>


<a href="{% url "admindashboard:imagetypes" %}"  class="btn btn-primary">{% trans "Back"%}</a>

</div>

{% endblock %}

admindashboard/templates/admindashboard/images/imagetype_form.html
	
{% extends 'admindashboard/base.html' %}
{% load i18n %}
{% load widget_tweaks %}
{% load django_bootstrap_breadcrumbs %}
{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb "Image Types" "admindashboard:imagetypes"  %}
    {% if not object %}
    {% breadcrumb "New Image Type" "admindashboard:imagetypecreate" %}
{% else %}
    {% breadcrumb "Update Image Type" "admindashboard:imagetypeupdate"  object.id %}
{% endif %}


{% endblock %}

{% block admin_page_content %}


 <div class="well well-md bs-component">
<form action={% if not object %}"{% url "admindashboard:imagetypecreate" %}"{% else %}"{% url "admindashboard:imagetypeupdate" object.id %}"{% endif %} method="post"  class="form-horizontal">

{% csrf_token %}
 <fieldset>
    <legend>
{% if not object %}
{% trans "New Image Type" %}
{% else %}
{% trans "Image Type" %}
{% endif %}
    </legend>

    {{ form.non_field_errors }}      
	{% for boundfield in form.visible_fields  %}
	{% trans boundfield.label as label %}
	<div class="form-group">
		{{ boundfield.errors }}
	    <label for="{{ boundfield.id }}" class="col-sm-2 control-label">{{label}}</label> 
	    <div class="col-md-8"> 	    	
			{{ boundfield |add_class:"form-control" }}
		</div>
	</div>
	{% endfor %}
 
	{% for boundfield in form.hidden_fields  %}	

			{{boundfield}}
	{% endfor %}


<div class="form-group">
   <div class="col-md-4 col-md-offset-2">
   {% if not readonly %} 
	    <input type="submit" class="btn btn-primary" value={% if not object %}   
{% trans "Create" %}{% else %}{% trans "Update" %}{% endif %} />
{% endif %}
	    <a href="{% url "admindashboard:imagetypes" %}"  class="btn btn-primary">{% trans "Back"%}</a>
			</div>
</div>



</fieldset>

</form>
</div>


{% endblock %}

admindashboard/templates/admindashboard/images/imagetype_list.html
{% extends 'admindashboard/base.html' %}
{% load i18n %}
{% load django_bootstrap_breadcrumbs %}
{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb "Image Types" "admindashboard:imagetypes"  %}
{% endblock %}

{% block admin_page_content %}

<div class="panel panel-primary">
 <div class="panel-heading">
 {% trans "Image Types" %}
 <div class="pull-right">
<a href="{% url "admindashboard:imagetypecreate" %}"  class="badge" role="button">{% trans "Add Image Type" %} <span class="glyphicon glyphicon-plus"></span></a> 
</div>
 </div>
  <div class="panel-body">
<table id="datatable" class="table table-hover table-striped table-condensed" >
<thead>
	<tr>
	<th>id</th>
	<th>name</th>
    <th>description</th>
    <th>display name</th>
	</tr>
</thead>
<tbody>
{% for imagetype in imagetype_list %}
<tr>
<td>{{imagetype.id}}</td>
<td>{{imagetype.name}}</td>
<td>{{imagetype.description}}</td>
<td>{{imagetype.display_name}}</td>
<td><a href="{% url "admindashboard:imagetype" imagetype.id %}" style="text-decoration:underline;">{{ customer.name }}</a></td>
<td><a href="{% url "admindashboard:imagetypedelete" imagetype.id %}"  class="glyphicon glyphicon-trash caution" role="button"></a>
<a href="{% url "admindashboard:imagetypeupdate" imagetype.id %}"  class="glyphicon glyphicon-pencil edit" role="button"></a>  

</td>
</tr>

{% endfor %}
</tbody>

</table>

  </div>
  <div class="panel-footer">
 {% if is_paginated %}

 <ul class="pagination pagination-sm">

 {% if page_obj.has_previous %}
  <li><a href="?page={{page_obj.previous_page}}">«</a></li>
  {% endif %}
  {% for page_idx in page_obj.paginator.page_range %}
  <li class="{% if page.number == page_idx %}active{% endif %}"><a href="?page={{page_idx}}">{{page_idx}}</a></li>
  {% endfor %}
  </ul>
   {% endif %}

</div>

          <a href="{% url "admindashboard:index" %}"  class="btn btn-primary">{% trans "Back" %}</a>

  	

 


  







{% endblock %}