admindashboard/urls.py
from django.conf.urls import patterns, url
# from organizations.backends import invitation_backend
import views
from registration.backends.default.views import ActivationView
from django.contrib.auth.views import *

urlpatterns = patterns('',

    url(r'^$', views.index, name='index'),

    url(r'^customers/$', views.CustomersListView.as_view(), name='customers'),
    url(r'^customers/create$', views.CustomerCreateView.as_view(), name='customercreate'),
    url(r'^customers/(?P<pk>\d+)/update$', views.CustomerUpdateView.as_view(), name='customerupdate'),
    url(r'^customers/(?P<pk>[-_\w]+)/$', views.CustomerView.as_view(), name='customer'),
    url(r'^customers/(?P<pk>\d+)/delete$', views.CustomerDeleteView.as_view(), name='customerdelete'),

    url(r'^customers/(?P<pk>\d+)/fields/create$', views.CustomerFieldCreate.as_view(), name='customerfieldcreate'),
    url(r'^customers/(?P<customer_id>\d+)/fields/(?P<pk>\d+)/delete$', views.CustomerFieldDeleteView.as_view(), name='customerfielddelete'),
    url(r'^customers/(?P<customer_id>\d+)/fields/(?P<pk>\d+)/update$', views.CustomerFieldUpdateView.as_view(), name='customerfieldupdate'),
    url(r'^customers/(?P<customer_id>\d+)/fields/(?P<pk>\d+)$', views.CustomerFieldDetailView.as_view(), name='customerfield'),

    url(r'^users/$', views.UsersListView.as_view(), name='users'),
    url(r'^users/create$', views.UserCreateView.as_view(), name='usercreate'),
    url(r'^users/(?P<pk>\d+)/update$', views.UserUpdateView.as_view(), name='userupdate'),
    url(r'^users/(?P<pk>[-_\w]+)/$', views.UserDetailView.as_view(), name='user'),

    url(r'^users/(?P<pk>\d+)/delete$', views.UserDeleteView.as_view(), name='userdelete'),

    url(r'^imagetypes$', views.ImageTypeListView.as_view(), name='imagetypes'),
    url(r'^imagetypes/(?P<pk>[-_\w]+)/$', views.ImageTypeView.as_view(), name='imagetype'),
    url(r'^imagetypes/create$', views.ImageTypeCreateView.as_view(), name='imagetypecreate'),
    url(r'^imagetypes/(?P<pk>\d+)/update$', views.ImageTypeUpdateView.as_view(), name='imagetypeupdate'),
    url(r'^imagetypes/(?P<pk>\d+)/delete$', views.ImageTypeDeleteView.as_view(), name='imagetypedelete'),
)

eiwa/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.generic.base import RedirectView
from django.contrib import admin
from django.core.urlresolvers import reverse_lazy
from django.conf.urls.static import static
from django.conf import settings

admin.autodiscover()



urlpatterns = patterns('',
    url(r'^ui/admin/', include(admin.site.urls)),
    url(r'^$', RedirectView.as_view(url=reverse_lazy('auth:login'))),
    url(r'^ui/', include('ui.urls', namespace='ui')),
    url(r'^auth/', include('login.urls', namespace='auth')),
    url(r'^admindashboard/', include('admindashboard.urls', namespace='admindashboard')),
)

# urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

ui/urls.py
from django.conf.urls import patterns, url
# from organizations.backends import invitation_backend
from .views import views

urlpatterns = patterns('',

    url(r'^(?P<client_id>\d+)/fields/$', views.customer_fields, name='fields'),
    url(r'^(?P<client_id>\d+)/fields/(?P<field_id>\d+)$', views.customer_field, name='field'),
    url(r'^(?P<client_id>\d+)/fields/(?P<field_id>\d+)/bucket/tabledata/$', views.customer_field_bucket_tabledata, name='field_bucket_tabledata'),
    url(r'^(?P<client_id>\d+)/fields/(?P<field_id>\d+)/border/tabledata/$', views.customer_field_border_tabledata, name='field_border_tabledata'),
    url(r'^(?P<client_id>\d+)/fields/(?P<field_id>\d+)/ol/$', views.customer_field_ol, name='fieldol'),
    url(r'^(?P<client_id>\d+)/fields/(?P<field_id>\d+)/env/kml/$', views.customer_field_env_kml, name='fieldenvkml'),
    url(r'^(?P<client_id>\d+)/fields/(?P<field_id>\d+)/border/kml/$', views.customer_field_border_kml, name='fieldborderkml'),
    url(r'^(?P<client_id>\d+)/fields/(?P<field_id>\d+)/bucket/tabledata/csv$', views.customer_field_bucket_data_export, name='field_bucket_tabledata_csv'),
    url(r'^(?P<client_id>\d+)/fields/(?P<field_id>\d+)/border/tabledata/csv$', views.customer_field_border_data_export, name='field_border_tabledata_csv'),

)

ui/models/basic.py
from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
import datetime
from pyproj import Geod


class Customer(models.Model):
    name = models.CharField(max_length=50)

    class Meta:
        db_table = 'ui_customer'
        app_label = 'ui'

    def __unicode__(self):
        return u'%s' % (self.name, )

    def get_absolute_url(self):
        return reverse('admindashboard:customer', args=[str(self.id)])

    def get_edit_url(self):
        return reverse('admindashboard:customerupdate', args=[str(self.id)])

    def getFolder(self):
        return self.name.lower().replace(" ", "")


class OrganizationUser(models.Model):
    user = models.OneToOneField(User, primary_key=True)
    customer = models.ForeignKey(Customer, blank=False)

    def get_absolute_url(self):
        return reverse('admindashboard:user', args=[str(self.id)])

    def get_edit_url(self):
        return reverse('admindashboard:userupdate', args=[str(self.user.id)])

    class Meta:
        db_table = 'ui_organizationuser'
        app_label = 'ui'


class Field(models.Model):
    name = models.CharField(max_length=50)
    customer = models.ForeignKey(Customer, blank=False, null=False)
    bordersFile = models.FileField(upload_to='static/', null=True)
    environmentsFile = models.FileField(upload_to='static/', null=True)

    class Meta:
        db_table = 'ui_field'
        app_label = 'ui'

    def __unicode__(self):
        return u'%s' % (self.name,)

    def getFolder(self):
        temp = self.name.lower().replace(" ", "")
        temp = temp.replace("-", "")
        return temp

    def getLastFolder(self):
        """ temporary method for retrieving last image folder for display.
        Ideally we would display all of them """
        date_folder = self.getAbsoluteFolder() + "/"
        images = self.productiveunitimage_set.all().order_by('-date_taken')
        if len(images) > 0:
            date_folder = images[0].getAbsoluteBaseFolder()

        return date_folder

    def getFalseColorFolder(self):
        return self.getLastFolder() + "tiles/falsecolor"

    def getNDVIFolder(self):
        return self.getLastFolder() + "tiles/ndvi"

    def getNDVIClassifiedFolder(self):
        return self.getLastFolder() + "tiles/ndviclassified"

    def getTerrainFolder(self):
        return self.getLastFolder() + "tiles/terrain"

    def getAbsoluteFolder(self):
        return self.customer.getFolder() + "/" + self.getFolder()

    def get_absolute_url(self):
        return reverse('admindashboard:field', args=[str(self.id)])

    def get_geom_center(self):
        g = Geod(ellps='WGS84')
        geoms = self.environmentgeom_set.all()
        if geoms:
            extent = geoms.extent()
            az12, az21, dist = g.inv(
                extent[0], extent[1], extent[2], extent[3])
            return g.fwd(extent[0], extent[1], az12, dist / 2)[1::-1]
        return []


class ImageType(models.Model):
    name = models.CharField(
        max_length=20, blank=False, null=False, unique=True)
    description = models.CharField(max_length=100)
    display_name = models.CharField(max_length=20, unique=True)

    def __unicode__(self):
        return u'%s' % (self.name, )

    def get_absolute_url(self):
        return reverse('admindashboard:imagetype', args=[str(self.id)])

    def get_edit_url(self):
        return reverse('admindashboard:imagetypeupdate', args=[str(self.id)])


def getFolder(instance, filename):
    path = instance.getAbsoluteBaseFolder()
    path = path + "originals/"
    return path + filename


class ProductiveUnitImage(models.Model):
    productive_unit = models.ForeignKey(Field)
    date_taken = models.DateField(default=datetime.date.today)

    image_type = models.ForeignKey(ImageType, null=True)
    image = models.ImageField(upload_to=getFolder, max_length=200)

    def getImageTypeFolder(self):
        value = self.image_type.name
        return "/" + value.lower().replace(" ", "")

    def getAbsoluteBaseFolder(self):
        path = self.productive_unit.getAbsoluteFolder()
        if self.date_taken:
            path = path + "{:/%Y/%m/%d/}".format(self.date_taken)
        return path

    def getImageTypeDescription(self):
        return self.image_type.name


from django.db.models.signals import post_save
# from django.contrib import messages
from decorators import disable_for_loaddata


@disable_for_loaddata
def my_callback(sender, **kwargs):
    """ Calls tiles generation method as an async task with celery """

    instance = kwargs['instance']
    if instance:
        from ..tasks import generate_tiles, error_handler, generation_completed
        generate_tiles.apply_async((instance,),
                                   link_error=error_handler.s(instance),
                                   link=generation_completed.s(instance))


post_save.connect(my_callback, sender=ProductiveUnitImage, weak=False)

ui/models/decorators.py
from functools import wraps


def disable_for_loaddata(signal_handler):
    """
    Decorator that turns off signal handlers when loading fixture data.
    """

    @wraps(signal_handler)
    def wrapper(*args, **kwargs):
        if kwargs['raw']:
            return
        signal_handler(*args, **kwargs)
    return wrapper

ui/views/decorators.py
from django.core.exceptions import PermissionDenied
from functools import wraps


def belong_to_customer_required(client_id=None):
    """
    Decorator for views that checks whether a user belongs to the customer he is trying
    to acces, redirecting to the log-in page if necessary.
    If the raise_exception parameter is given the PermissionDenied exception
    is raised.
    """
    def wrapped(client_id=None):
        # First check if the user has the permission (even anon users)
        if client_id:
            if user.organizationuser.customer.id == client_id:
                return func(request, *args, **kwargs)
            # In case the 403 handler should be called raise the exception
            # if raise_exception:
            #     raise PermissionDenied
            # # As the last resort, show the login form
            #     return HttpResponseRedirect(reverse('login'))

    return wraps(func)(wrapped)

ui/views/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.http import Http404
from django.contrib.gis.shortcuts import render_to_kml
from django.contrib import messages

from ..models import EnvironmentGeom, BorderGeom, Field, Customer

# TODO convert validation logic to decorator
@login_required
def customer_fields(request, client_id):
    try:
        if not client_id:
            raise Http404
        customer = Customer.objects.get(pk=client_id)

        if str(request.user.organizationuser.customer.id) != client_id:
            if not request.user.groups.filter(name="Admin").exists():
                raise Http404

    except Field.DoesNotExist:
        raise Http404
    return render(request, 'ui/field_list.html', {'customer': customer,
                                                  'field_list':
                                                  customer.field_set.all()})


@login_required
def customer_field(request, client_id, field_id):
    try:
        field = Field.objects.get(pk=field_id)
    except Field.DoesNotExist:
        raise Http404

    return render(request, 'ui/field.html', {
        'field': field,
        'filter_data_env': EnvironmentGeom.getMetadata(field),
        'filter_data_border': BorderGeom.getMetadata(field),
        'geometry_center': list(field.get_geom_center()),
        'filter_images_dates': [d.strftime('%Y/%m/%d') for d in field.productiveunitimage_set.
                                    values_list('date_taken', flat=True).
                                    order_by('date_taken').distinct()]
    })


@login_required
def customer_field_border_tabledata(request, client_id, field_id):
    try:
        field_data = EnvironmentGeom.objects.filter(
            productive_unit_id=field_id)
        from django.core import serializers
        data = serializers.serialize("python", field_data)

    except Field.DoesNotExist:
        raise Http404

    return render(request, 'ui/field_datasheet.html',  {
        'columns': BorderGeom.getMetadataColumns(field_id),
        'field_data': data,
    })


@login_required
def customer_field_bucket_tabledata(request, client_id, field_id):
    try:
        field_data = EnvironmentGeom.objects.filter(
            productive_unit_id=field_id)
        from django.core import serializers
        data = serializers.serialize("python", field_data)

    except Field.DoesNotExist:
        raise Http404

    return render(request, 'ui/field_datasheet.html',
                  {'columns': EnvironmentGeom.getMetadataColumns(field_id),
                   'field_data': data,
                   })


@login_required
def customer_field_ol(request, client_id, field_id):
    try:
        field = Field.objects.get(pk=field_id)
    except Field.DoesNotExist:
        raise Http404

    return render(request, 'ui/ol.html', {
        'field': field,
        'filter_data_env': EnvironmentGeom.getMetadata(field),
        'filter_data_border': BorderGeom.getMetadata(field)
    })


#@login_required removed to be able to query the server from localhost - FIXME
def customer_field_env_kml(request, client_id, field_id):
    try:
        filters = request.GET
        field = Field.objects.get(pk=field_id)
        return render_to_kml("gis/kml/placemarks_custom.kml",
                             {'places': EnvironmentGeom.objects.filter(
                                 productive_unit=field,
                                 **parseKmlFilterParams(filters)).kml,
                               'line_color': 'ffff0000'})

    except Field.DoesNotExist:
        raise Http404


#@login_required removed to be able to query the server from localhost - FIXME
def customer_field_border_kml(request, client_id, field_id):
    try:
        filters = request.GET
        field = Field.objects.get(pk=field_id)
        return render_to_kml("gis/kml/placemarks_custom.kml",
                             {'places': BorderGeom.objects.filter(
                                 productive_unit=field,
                                 **parseKmlFilterParams(filters)).kml,
                             'line_color': 'DD083300'})
    except Field.DoesNotExist:
        raise Http404


import csv
from django.http import HttpResponse


def customer_field_bucket_data_export(request, client_id, field_id):
    # Create the HttpResponse object with the appropriate CSV header.
    response = HttpResponse(content_type='text/csv')

    try:
        field_data = EnvironmentGeom.objects.filter(productive_unit=field_id)
        if len(field_data) == 0:
            raise Http404

        response['Content-Disposition'] = 'attachment; filename={}.csv'.format(
            field_data[0].productive_unit.name)

        writer = csv.writer(response)

        columns = EnvironmentGeom.getMetadataColumns(field_id)

        writer.writerow(columns)
        for geom in field_data:
            writer.writerow([geom.info[c] for c in columns])

    except Field.DoesNotExist:
        raise Http404

    return response


def customer_field_border_data_export(request, client_id, field_id):
    # Create the HttpResponse object with the appropriate CSV header.
    response = HttpResponse(content_type='text/csv')

    try:
        field_data = EnvironmentGeom.objects.filter(productive_unit=field_id)
        if len(field_data) == 0:
            raise Http404

        response['Content-Disposition'] = 'attachment; filename={}.csv'.format(
            field_data[0].productive_unit.name)

        writer = csv.writer(response)

        columns = EnvironmentGeom.getMetadataColumns(field_id)

        writer.writerow(columns)
        for geom in field_data:
            writer.writerow([geom.info[c] for c in columns])

    except Field.DoesNotExist:
        raise Http404

    return response


def parseKmlFilterParams(params_encoded):
    d = {}
    if params_encoded is None:
        return d
    for k, v in params_encoded.lists():
        if k != 'gm':
            value = v
            if len(v) == 1:
                value = v[0]

            if k.find("info__") == 0:
                nd = d.get(k[0:k.find("__", 6)], {})
                nd.update({k[k.find("__", 6) + 2:]: value})
                d[k[0:k.find("__", 6)]] = nd

            else:
                d[k] = v
                
    return d

ui/templates/ui/field.html
{% extends 'base.html' %}

{% load static %}
{% load i18n %}
{% block extrastyle %}
<link rel="stylesheet" href='{% static "ui/css/bootstrap-slider.css" %}'>

<style type="text/css">

    html { height: 100% }
    body { height: 100% }
    .container-fluid, .row, #map-canvas , .google-maps-canvas,.col-sm-9 ,.col-sm-offset-3 ,.col-md-10 ,.col-md-offset-2 ,.main, .tab-pane ,.active, .tab-content { height: 100% }

	.container-fluid { height: 95% }

	.slider-selection {
	/*background: #8283FF;*/
		background: #DCDDF5
	}

        #slider-image-date .slider-handle.custom {
            position: absolute;
            width: 25px;
            height: 25px;
            border: 1px solid #FFF;
            background: #ECBE93;
            opacity: 1;
            display: inline-block;
            font-family: FontAwesome;
            font-style: normal;
            font-weight: normal;
            line-height: 1;
            text-align: center;
            vertical-align: bottom;
            line-height: 22px;
            font-size: 10px;
            
            border-radius: 50%;
            padding-top:3.5px;
            
        }

        #slider-image-date .slider-selection {
                background: #ECBE93
        }
            
        #slider-image-date .slider-handle.custom::before {
              content: '\f017'; 
              color: #F13511;
            }

	</style>
{% endblock  %}

{%  block extraheadjs %}
<script>

    var key='AIzaSyA3eC-QHrw6JQfrG0mc6nInA0hPPbfh9To';
    var filter_data_env =JSON.parse("{{ filter_data_env | escapejs }}")
    var filter_data_border =JSON.parse("{{ filter_data_border | escapejs }}")
    var field_id = {{field.id}}
    {% get_media_prefix as media_prefix %}
    var image_folder ='{{ media_prefix |add:field.customer.getFolder|add:"/" |add:field.getFolder }}'

    var geometry_center = {{ geometry_center }}
    var filter_images_dates = {{  filter_images_dates | safe }}
    var overlayMapTypes = []
</script>


<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&key=AIzaSyA3eC-QHrw6JQfrG0mc6nInA0hPPbfh9To&sensor=false"></script>

<script src='{% static "ui/js/bootstrap-slider.min.js" %}'></script>
<script src='{% static "ui/js/docs.min.js" %}'></script>

{% endblock %}

{% block organization_name %} {{ field.customer.name }}{% endblock %}

{% block extranav %}

    <ul class="nav navbar-nav">
        <li class="navbar-collapse collapse">
            <ul class="nav navbar-nav nav-pills ">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"> {{field.name}}<b class="caret"></b></a>
                    <ul class="dropdown-menu">

                        {% for productive_unit in field.customer.field_set.all %}
                            <li><a href="{% url "ui:field" productive_unit.customer.id productive_unit.id %}">{{productive_unit.name}}</a></li>
                        {% endfor %}

                    </ul>
                </li>
                <li id="maptab" class="active"><a href="#mapa" data-toggle="tab">Mapa</a></li>
                <li id="tabletab"><a href="#tabla" data-toggle="tab">Tabla</a></li>

            </ul>

        </li>
    </ul>
    {% if user.organizationuser.customer.name == 'Eiwa' %}
    <ul class="nav navbar-nav nav-pills">
    <li><a href="{% url 'admindashboard:customers' %}">{% trans "Clientes" %}</a></li>
     <li class="divider-vertical"></li>
    <li><a href="{% url 'admindashboard:users' %}">{% trans "Users" %}</a></li>
    <li><a href="{% url 'admindashboard:imagetypes' %}">{% trans "Image Types" %}</a></li>
   </ul>  
   {% endif %}


{% endblock %}


{% block sidebar %}
    <div class="sidebar">
        <ul class="nav nav-sidebar">
            <div class="panel-group" id="accordion">
                <div class="panel panel-default">
                <div class="panel-heading" role="tab">
                  <h4 class="panel-title">
                    <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapse_rasters" aria-expanded="true" aria-controls="collapse_rasters"><h6>Mosaicos<span class="glyphicon glyphicon-chevron-down pull-right"></span></h6></a>
                  </h4>
                </div>
                <div id="collapse_rasters" class="panel-collapse collapse in" role='tabpanel'>
                  <div class="panel-body">
                        <ul class="col-sm-offset-1 nav" id="rasters_list">
                            <li>                
                                {% with field.productiveunitimage_set.all|dictsort:"image_type.name"  as image_type_list_sorted %}
                                  {% if image_type_list_sorted|length > 0 %}
                                    {% regroup image_type_list_sorted by image_type.name as image_type_list %}
                                     
                                    {% for image_type in image_type_list %}
                                       <script type="text/javascript">overlayMapTypes.push('{{image_type.grouper | lower | cut:" "}}') ; console.log(overlayMapTypes)</script> 
                                        <div class="checkbox">
                                            <input type="checkbox" class="chk_layer" id="chk_{{image_type.grouper | lower | cut:" "}}" data-layer-type='raster' data-layer='{{image_type.grouper| lower | cut:" "}}' data-basemap='{% if forloop.last %}true{% else %}false{% endif %}'>{{image_type.list.0.image_type.display_name}}</input>
                                        </div>
                                    {% endfor %}
                                    {% else %}
                                       <script type="text/javascript">overlayMapTypes = ['terrain', 'falsecolor', 'ndvi', 'ndviclassified']</script> 
                    <div class="checkbox" >
                        <input type="checkbox" class="chk_layer" id="chk_falsecolor" data-layer="falsecolor" data-layer-type='raster'>False Color Rasters</input>
                    </div>
                    <div class="checkbox" >
                        <input type="checkbox" class="chk_layer" id="chk_ndvi" data-layer="ndvi" data-layer-type='raster'>NDVI</input>
                    </div>
                    <div class="checkbox" >
                        <input type="checkbox" class="chk_layer" id="chk_ndviclassified" data-layer="ndviclassified" data-layer-type='raster'>NDVI Classified</input>
                    </div>
                    <div class="checkbox" >
                        <input type="checkbox" class="chk_layer" id="chk_terrain" data-layer="terrain" data-layer-type='raster'>Terrain</input>
                    </div>
                                    {% endif %}
                                {% endwith %}   
                            </li>
                        </ul>
                  </div>
                </div>
              </div>

                <div class="panel panel-default">
                <div class="panel-heading">
                  <h4 class="panel-title">
                    <a data-toggle="collapse" data-parent="#accordion" href="#collapse_shapes" aria-expanded="false" aria-controls="collapse_shapes"><h6>Ambientes<span class="glyphicon glyphicon-chevron-right pull-right"></span></h6></a>
                  </h4>
                </div>
                <div id="collapse_shapes" class="panel-collapse collapse">
                  <div class="panel-body">
                        <ul class="col-sm-offset-1 nav" id="shapes_list">
                            <li>                
                                <!--div class="checkbox">
                                    <input type="checkbox" class="chk_layer" id="chk_borders" data-layer="borders">Contorno</input>
                                </div-->
                                <div class="checkbox" >
                                    <input type="checkbox" class="chk_layer" id="chk_environments" data-layer="environments">{% if field.customer.name == "Bayer" %}Líneas{% else %}Parcelas{% endif %}</input>
                                </div>
                            </li>
                        </ul>
                  </div>
                </div>
              </div>


            <div class="panel panel-default">
                <div class="panel-heading">
                  <h4 class="panel-title">
                    <a data-toggle="collapse" data-parent="#accordion" href="#collapse_shapeenv_filters"><h6>Filtrar por Ambiente   <span class="glyphicon glyphicon-chevron-right pull-right"></span></h6></a>
                  </h4>
                </div>
                <div id="collapse_shapeenv_filters" class="panel-collapse collapse">
                  <div class="panel-body">
                    	<ul class="col-sm-offset-1 nav" id="environments"></ul>
                  </div>
                </div>
              </div>
              <div class="panel panel-default">
                <div class="panel-heading">
                  <h4 class="panel-title">
                    <a data-toggle="collapse" data-parent="#accordion" href="#collapse_shapeborder_filters"><h6>Filtrar por Contorno   <span class="glyphicon glyphicon-chevron-right pull-right"></span></h6></a>
                  </h4>
                </div>
                <div id="collapse_shapeborder_filters" class="panel-collapse collapse">
                  <div class="panel-body">
                    <ul class="col-sm-offset-1 nav" id="borders"></ul>
                  </div>
                </div>
              </div>
            </div>
        </ul>
    </div>

{% endblock  %}
{% block body_block  %}
    <div class="tab-content">
        <div class="tab-pane active" id="mapa">
                <div id="map-canvas"></div>
                <div id="image-date-filter"></div>
                <div id="latlong"></div>
        </div>
        <div class="tab-pane" id="tabla">
             <row>
                <div id="actions-bar" class="col-sm-offset-11">
                    <a type="button" class="btn btn-warning btn-sm" href="{% url "ui:field_bucket_tabledata_csv"  field.customer.id field.id %}">
                            <span class="glyphicon glyphicon-download"></span> CSV
                    </a>   
                </div>
            </row>
            <row>
                <div  id="table_container_bucket"></div>
            </row>
        </div>
    </div>

{% endblock  %}

{% block extrabottomjs %}
    <script src='{% static "ui/js/eiwa.js" %}'></script>
    <script>

     $('.panel-default').on('show.bs.collapse', function () {
             $(this).addClass('active');
             $(".glyphicon",this).removeClass("glyphicon-chevron-right").addClass("glyphicon-chevron-down")
        });

        $('.panel-default').on('hide.bs.collapse', function () {
             $(this).removeClass('active');
               $(".glyphicon",this).removeClass("glyphicon-chevron-down").addClass("glyphicon-chevron-right")
        });

    // ADD SLIDEDOWN ANIMATION TO DROPDOWN //
    $('.dropdown').on('show.bs.dropdown', function(e){
      $(this).find('.dropdown-menu').first().stop(true, true).slideDown(200);
    });

    // ADD SLIDEUP ANIMATION TO DROPDOWN //
    $('.dropdown').on('hide.bs.dropdown', function(e){
      $(this).find('.dropdown-menu').first().stop(true, true).slideUp(200);
    });
    </script>
{% endblock %}

ui/templates/ui/field_datasheet.html
{% load extra_tags %}
{% load i18n %}

{% if field_data %}

<table id="datatable" class="table table-hover table-striped table-condensed" >
     
    <thead>

  <tr>
  <th>
  Number
  </th>
  {% for column in columns %}
    <th>
        {{ column }}
        </th>
    
{% endfor %}
</tr>
</thead>
<tbody>
  {% for row in field_data %}
  <tr>
    <td>{{ row.fields.number}}</td> 
    {% for column in columns %}
        <td>{{ row.fields.info | access:column}}</td>
    {% endfor %}    
    </tr>
{% endfor %}
  </tbody>

 </table> 

{% else %}

    <p>{% trans "There is no data to display" %}</p>
{% endif %}

ui/templates/ui/field_list.html
{% extends 'base.html' %}
{% load i18n %}
{% block organization_name %} {{ customer.name }}{% endblock %}
{% block extranav %} 
{% if user.organizationuser.customer.name == 'Eiwa' %}
<ul class="nav navbar-nav nav-pills">
    <li><a href="{% url 'admindashboard:customers' %}">{% trans "Clientes" %}</a></li>
     <li class="divider-vertical"></li>
    <li><a href="{% url 'admindashboard:users' %}">{% trans "Users" %}</a></li>
    <li><a href="{% url 'admindashboard:imagetypes' %}">{% trans "Image Types" %}</a></li>
   </ul>  
{% endif %}
{% endblock %}
{% block body_block %}
{% if field_list %}
    <ul>
    {% for field in field_list %}
        <li><a id="field_{{field.id}}" href="{% url "ui:field" field.customer.id field.id %}">{{ field.name }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>{% trans "There are no assigned fields" %}</p>
{% endif %}

{% endblock %}