admindashboard/urls.py
from django.conf.urls import patterns, url
# from organizations.backends import invitation_backend
import views
from registration.backends.default.views import ActivationView
from django.contrib.auth.views import *

urlpatterns = patterns('',

    url(r'^$', views.index, name='index'),

    url(r'^customers/$', views.CustomersListView.as_view(), name='customers'),
    url(r'^customers/create$', views.CustomerCreateView.as_view(), name='customercreate'),
    url(r'^customers/(?P<pk>\d+)/update$', views.CustomerUpdateView.as_view(), name='customerupdate'),
    url(r'^customers/(?P<pk>[-_\w]+)/$', views.CustomerView.as_view(), name='customer'),
    url(r'^customers/(?P<pk>\d+)/delete$', views.CustomerDeleteView.as_view(), name='customerdelete'),

    url(r'^customers/(?P<pk>\d+)/fields/create$', views.CustomerFieldCreate.as_view(), name='customerfieldcreate'),
    url(r'^customers/(?P<customer_id>\d+)/fields/(?P<pk>\d+)/delete$', views.CustomerFieldDeleteView.as_view(), name='customerfielddelete'),
    url(r'^customers/(?P<customer_id>\d+)/fields/(?P<pk>\d+)/update$', views.CustomerFieldUpdateView.as_view(), name='customerfieldupdate'),
    url(r'^customers/(?P<customer_id>\d+)/fields/(?P<pk>\d+)$', views.CustomerFieldDetailView.as_view(), name='customerfield'),

    url(r'^users/$', views.UsersListView.as_view(), name='users'),
    url(r'^users/create$', views.UserCreateView.as_view(), name='usercreate'),
    url(r'^users/(?P<pk>\d+)/update$', views.UserUpdateView.as_view(), name='userupdate'),
    url(r'^users/(?P<pk>[-_\w]+)/$', views.UserDetailView.as_view(), name='user'),

    url(r'^users/(?P<pk>\d+)/delete$', views.UserDeleteView.as_view(), name='userdelete'),

    url(r'^imagetypes$', views.ImageTypeListView.as_view(), name='imagetypes'),
    url(r'^imagetypes/(?P<pk>[-_\w]+)/$', views.ImageTypeView.as_view(), name='imagetype'),
    url(r'^imagetypes/create$', views.ImageTypeCreateView.as_view(), name='imagetypecreate'),
    url(r'^imagetypes/(?P<pk>\d+)/update$', views.ImageTypeUpdateView.as_view(), name='imagetypeupdate'),
    url(r'^imagetypes/(?P<pk>\d+)/delete$', views.ImageTypeDeleteView.as_view(), name='imagetypedelete'),
)

eiwa/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.generic.base import RedirectView
from django.contrib import admin
from django.core.urlresolvers import reverse_lazy
from django.conf.urls.static import static
from django.conf import settings

admin.autodiscover()



urlpatterns = patterns('',
    url(r'^ui/admin/', include(admin.site.urls)),
    url(r'^$', RedirectView.as_view(url=reverse_lazy('auth:login'))),
    url(r'^ui/', include('ui.urls', namespace='ui')),
    url(r'^auth/', include('login.urls', namespace='auth')),
    url(r'^admindashboard/', include('admindashboard.urls', namespace='admindashboard')),
)

# urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

ui/urls.py
from django.conf.urls import patterns, url
# from organizations.backends import invitation_backend
from .views import views

urlpatterns = patterns('',

    url(r'^(?P<client_id>\d+)/fields/$', views.customer_fields, name='fields'),
    url(r'^(?P<client_id>\d+)/fields/(?P<field_id>\d+)$', views.customer_field, name='field'),
    url(r'^(?P<client_id>\d+)/fields/(?P<field_id>\d+)/bucket/tabledata/$', views.customer_field_bucket_tabledata, name='field_bucket_tabledata'),
    url(r'^(?P<client_id>\d+)/fields/(?P<field_id>\d+)/border/tabledata/$', views.customer_field_border_tabledata, name='field_border_tabledata'),
    url(r'^(?P<client_id>\d+)/fields/(?P<field_id>\d+)/ol/$', views.customer_field_ol, name='fieldol'),
    url(r'^(?P<client_id>\d+)/fields/(?P<field_id>\d+)/env/kml/$', views.customer_field_env_kml, name='fieldenvkml'),
    url(r'^(?P<client_id>\d+)/fields/(?P<field_id>\d+)/border/kml/$', views.customer_field_border_kml, name='fieldborderkml'),
    url(r'^(?P<client_id>\d+)/fields/(?P<field_id>\d+)/bucket/tabledata/csv$', views.customer_field_bucket_data_export, name='field_bucket_tabledata_csv'),
    url(r'^(?P<client_id>\d+)/fields/(?P<field_id>\d+)/border/tabledata/csv$', views.customer_field_border_data_export, name='field_border_tabledata_csv'),

)

ui/models/basic.py
from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
import datetime
from pyproj import Geod


class Customer(models.Model):
    name = models.CharField(max_length=50)

    class Meta:
        db_table = 'ui_customer'
        app_label = 'ui'

    def __unicode__(self):
        return u'%s' % (self.name, )

    def get_absolute_url(self):
        return reverse('admindashboard:customer', args=[str(self.id)])

    def get_edit_url(self):
        return reverse('admindashboard:customerupdate', args=[str(self.id)])

    def getFolder(self):
        return self.name.lower().replace(" ", "")


class OrganizationUser(models.Model):
    user = models.OneToOneField(User, primary_key=True)
    customer = models.ForeignKey(Customer, blank=False)

    def get_absolute_url(self):
        return reverse('admindashboard:user', args=[str(self.id)])

    def get_edit_url(self):
        return reverse('admindashboard:userupdate', args=[str(self.user.id)])

    class Meta:
        db_table = 'ui_organizationuser'
        app_label = 'ui'


class Field(models.Model):
    name = models.CharField(max_length=50)
    customer = models.ForeignKey(Customer, blank=False, null=False)
    bordersFile = models.FileField(upload_to='static/', null=True)
    environmentsFile = models.FileField(upload_to='static/', null=True)

    class Meta:
        db_table = 'ui_field'
        app_label = 'ui'

    def __unicode__(self):
        return u'%s' % (self.name,)

    def getFolder(self):
        temp = self.name.lower().replace(" ", "")
        temp = temp.replace("-", "")
        return temp

    def getLastFolder(self):
        """ temporary method for retrieving last image folder for display.
        Ideally we would display all of them """
        date_folder = self.getAbsoluteFolder() + "/"
        images = self.productiveunitimage_set.all().order_by('-date_taken')
        if len(images) > 0:
            date_folder = images[0].getAbsoluteBaseFolder()

        return date_folder

    def getFalseColorFolder(self):
        return self.getLastFolder() + "tiles/falsecolor"

    def getNDVIFolder(self):
        return self.getLastFolder() + "tiles/ndvi"

    def getNDVIClassifiedFolder(self):
        return self.getLastFolder() + "tiles/ndviclassified"

    def getTerrainFolder(self):
        return self.getLastFolder() + "tiles/terrain"

    def getAbsoluteFolder(self):
        return self.customer.getFolder() + "/" + self.getFolder()

    def get_absolute_url(self):
        return reverse('admindashboard:field', args=[str(self.id)])

    def get_geom_center(self):
        g = Geod(ellps='WGS84')
        geoms = self.environmentgeom_set.all()
        if geoms:
            extent = geoms.extent()
            az12, az21, dist = g.inv(
                extent[0], extent[1], extent[2], extent[3])
            return g.fwd(extent[0], extent[1], az12, dist / 2)[1::-1]
        return []


class ImageType(models.Model):
    name = models.CharField(
        max_length=20, blank=False, null=False, unique=True)
    description = models.CharField(max_length=100)
    display_name = models.CharField(max_length=20, unique=True)

    def __unicode__(self):
        return u'%s' % (self.name, )

    def get_absolute_url(self):
        return reverse('admindashboard:imagetype', args=[str(self.id)])

    def get_edit_url(self):
        return reverse('admindashboard:imagetypeupdate', args=[str(self.id)])


def getFolder(instance, filename):
    path = instance.getAbsoluteBaseFolder()
    path = path + "originals/"
    return path + filename


class ProductiveUnitImage(models.Model):
    productive_unit = models.ForeignKey(Field)
    date_taken = models.DateField(default=datetime.date.today)

    image_type = models.ForeignKey(ImageType, null=True)
    image = models.ImageField(upload_to=getFolder, max_length=200)

    def getImageTypeFolder(self):
        value = self.image_type.name
        return "/" + value.lower().replace(" ", "")

    def getAbsoluteBaseFolder(self):
        path = self.productive_unit.getAbsoluteFolder()
        if self.date_taken:
            path = path + "{:/%Y/%m/%d/}".format(self.date_taken)
        return path

    def getImageTypeDescription(self):
        return self.image_type.name


from django.db.models.signals import post_save
# from django.contrib import messages
from decorators import disable_for_loaddata


@disable_for_loaddata
def my_callback(sender, **kwargs):
    """ Calls tiles generation method as an async task with celery """

    instance = kwargs['instance']
    if instance:
        from ..tasks import generate_tiles, error_handler, generation_completed
        generate_tiles.apply_async((instance,),
                                   link_error=error_handler.s(instance),
                                   link=generation_completed.s(instance))


post_save.connect(my_callback, sender=ProductiveUnitImage, weak=False)

admindashboard/forms.py
from django.forms import ModelForm, DateInput, DateField
from django.forms.models import inlineformset_factory, BaseInlineFormSet
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from functools import partial

date_format = '%d/%m/%Y'
DateInputCustom = partial(
    DateInput, format=(date_format), attrs={'class': 'datepicker'})

from ui.models import Field, ProductiveUnitImage, OrganizationUser

class CustomerFieldForm(ModelForm):

    class Meta:
        model = Field
        exclude = ('customer', 'delete', )


class UserCreateForm(UserCreationForm):

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email', 'username',
                  'password1', 'password2', 'groups', )


class UserEditForm(UserChangeForm):

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email', 'username',
                  'password', 'groups', 'is_active', )


class NoEmptyInlineModelFormSet(BaseInlineFormSet):

    def __init__(self, *args, **kwargs):
        super(NoEmptyInlineModelFormSet, self).__init__(*args, **kwargs)
        for form in self.forms:
            form.empty_permitted = False


class ProductiveUnitImageForm(ModelForm):
    date_taken = DateField(
        widget=DateInputCustom(), input_formats=(date_format,))

    class Meta:
        model = ProductiveUnitImage
        fields = '__all__'

OrganizationUserFormSet = inlineformset_factory(User, OrganizationUser,
                                                can_delete=False,
                                                extra=1,
                                                formset=NoEmptyInlineModelFormSet)

ProductiveUnitImageFormSet = inlineformset_factory(Field, ProductiveUnitImage,
                                                   form=ProductiveUnitImageForm,
                                                   can_delete=True,
                                                   extra=1, max_num=1)

admindashboard/templates/admindashboard/customers/customer_detail.html
{% extends 'admindashboard/base.html' %}
{% load i18n %}
{% load widget_tweaks %}
{% load django_bootstrap_breadcrumbs %}

{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb "Clients" "admindashboard:customers" %}
    {% breadcrumb customer.name "admindashboard:customer" customer.id %}
{% endblock %}


{% block admin_page_content %}
<div class="row  col-sm-10">
<div class="well well-sm bs-component">
<legend>
  {% trans "Client" %}
  </legend>
   <label class="col-sm-1 col-md-2">
    {% trans "Name" %}:  </label>    {{customer.name}}
</div>
</div>
<div class="row  col-sm-10">
<div class="panel panel-primary">
 <div class="panel-heading">
{% trans "Fields" %}
 </div>
  <div class="panel-body">
 

<table id="datatable" class="table table-hover table-striped table-condensed" >
<thead>
	<tr>
	
	<th>{% trans "Name" %}</th>
  <th>{% trans "Environment" %}</th>
  <th>{% trans "Borders" %}</th>
	</tr>

</thead>
<tbody>
{% for field in object.field_set.all %}
<tr>

<td>{{ field.name }}</td>
<td>{{ field.environmentsFile }}</td>
<td>{{ field.bordersFile }}</td>
</tr>

{% endfor %}
</tbody>

</table>

  </div>
</div>
</div>
<div class="row  col-sm-10">
<a href="{% url "admindashboard:customers" %}"  class="btn btn-primary">{% trans "Back" %}</a>
</div>
{% endblock %}

admindashboard/templates/admindashboard/customers/customer_form.html
{% extends 'admindashboard/base.html' %}
{% load i18n %}
{% load widget_tweaks %}
{% load django_bootstrap_breadcrumbs %}
{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb "Clients" "admindashboard:customers" %}
    {% if customer %}
    {% breadcrumb "Edit Client" "admindashboard:customerupdate" customer.id %}
    {% else %}
    {% breadcrumb "New Client" "admindashboard:customercreate" %}
    {% endif %}
{% endblock %}

{% block admin_page_content %}

<div class="well well-sm bs-component">

<form action="{{ action }}" method="post"  class="form-horizontal">
<fieldset>

{% csrf_token %}
<legend>{% if customer %}
{% trans "Edit Client" %} 
{% else %}
{% trans "New Client" %}
{% endif %}</legend>

{{ form.non_field_errors }} 
{% for boundfield in form  %}

{% trans boundfield.label as label %}
<div class="form-group">    
      {{ boundfield.errors }}
    <label for="{{ boundfield.id }}" class="col-sm-1 control-label">{{label}}</label> 
    <div class="col-sm-6"> 
      {{ boundfield |add_class:"form-control" }}
    </div>
</div>

{% endfor %}

{% trans "Update" as update %}
{% trans "Create" as create %}
<div class="form-group">
   <div class="col-sm-4 col-sm-offset-1">
    <input type="submit" class="btn btn-primary" value="{% if customer %}{{update}}{% else %}{{create}}{% endif %}"/>
      <a href="{% url "admindashboard:customers" %}"  class="btn btn-primary">{% trans "Back" %}</a>
  </div>
</div>




</fieldset>
</form>

</div>
</div>
<div class="row  col-sm-10">


{% if customer %}

<div class="panel panel-primary">
 <div class="panel-heading">
{% trans "Fields" %}
 <div class="pull-right">
<a href="{% url "admindashboard:customerfieldcreate" customer.id %}"  class="badge" >{% trans "Add Field" %} <span class="glyphicon glyphicon-plus"></span></a> 
</div>

 </div>
  <div class="panel-body">
 

<table id="datatable" class="table table-hover table-striped table-condensed" >
<thead>
    <tr>
    
    <th>{% trans "Name" %}</th>
  <th>{% trans "Environment" %}</th>
  <th>{% trans "Borders" %}</th>
    </tr>

</thead>
<tbody>
{% for field in object.field_set.all %}
<tr>

<td>{{ field.name }}</td>
<td>{{ field.environmentsFile }}</td>
<td>{{ field.bordersFile }}</td>
<td>
<a href="{% url "admindashboard:customerfielddelete" customer.id field.id %}"  class="glyphicon glyphicon-trash caution" role="button"></a>
<a href="{% url "admindashboard:customerfieldupdate" customer.id field.id %}"  class="glyphicon glyphicon-pencil edit" role="button"></a> 
<a href="{% url "admindashboard:customerfield"  customer.id field.id %}"  class="glyphicon glyphicon-zoom-in" role="button"></a> 
</td>
</tr>

{% endfor %}
</tbody>

</table>

  </div>
</div>
{% endif %}

{% endblock %}

admindashboard/templates/admindashboard/customers/customer_list.html
{% extends 'admindashboard/base.html' %}
{% load i18n %}
{% load django_bootstrap_breadcrumbs %}

{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb "Clients" "admindashboard:customers" %}
{% endblock %}

{% block admin_page_content %}

{{ block.super }}
<div class="panel panel-primary">
 <div class="panel-heading">
 {% trans "Clients" %}
 <div class="pull-right">
<a href="{% url "admindashboard:customercreate" %}"  class="badge" role="button">{% trans "Add Client" %} <span class="glyphicon glyphicon-plus"></span></a> 
</div>
 </div>
  <div class="panel-body">
<table id="datatable" class="table table-hover table-striped table-condensed" >
<thead>
	<tr>
	<th>id</th>
	<th>name</th>
	</tr>

</thead>
<tbody>
{% for customer in customer_list %}
<tr><td>{{customer.id}}</td>
<td><a href="{% url "admindashboard:customer" customer.id %}" style="text-decoration:underline;">{{ customer.name }}</a></td>
<td><a href="{% url "admindashboard:customerdelete" customer.id %}"  class="glyphicon glyphicon-trash caution" role="button"></a>
<a href="{% url "admindashboard:customerupdate" customer.id %}"  class="glyphicon glyphicon-pencil edit" role="button"></a>  
<a href="{% url "ui:fields" customer.id %}"  class="glyphicon glyphicon-log-in" role="button"></a> 

</td>
</tr>

{% endfor %}
</tbody>

</table>

  </div>
  <div class="panel-footer">
 {% if is_paginated %}

 <ul class="pagination pagination-sm">

 {% if page_obj.has_previous %}
  <li><a href="?page={{page_obj.previous_page}}">«</a></li>
  {% endif %}
  {% for page_idx in page_obj.paginator.page_range %}
  <li class="{% if page.number == page_idx %}active{% endif %}"><a href="?page={{page_idx}}">{{page_idx}}</a></li>
  {% endfor %}
  </ul>
   {% endif %}

</div>

          <a href="{% url "admindashboard:index" %}"  class="btn btn-primary">{% trans "Back" %}</a>

  	

 


  







{% endblock %}